version: '3'

services:
  chattastic:
    build: .
    container_name: chattastic
    ports:
      - "8000:8000"
    volumes:
      - ./emote_cache:/app/emote_cache
      - ./debug_screenshots:/app/debug_screenshots
      - ./selenium_chrome_data:/app/selenium_chrome_data
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    shm_size: 2g  # Increase shared memory for Chrome
    restart: unless-stopped
