version: '3'

services:
  docker-desktop-viewer:
    build: .
    container_name: docker-desktop-viewer
    ports:
      - "8000:8000"
    volumes:
      - ./debug_screenshots:/app/debug_screenshots
      - ./:/app/host_settings
      # Uncomment the line below to enable Docker API functionality
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    shm_size: 2g  # Shared memory for X display
    restart: unless-stopped
